### ISSUE TITLE
Unable to install autofps due to error

### ISSUE THREAD

**Issue by SHAshton** [ResetXPDR/MSFS2020_AutoFPS#8] opened 2024-02-29 03:09 UTC
In trying to install this I'm getting the error :  exception 'System.IO.DirectoryNotFoundException' during AutoStartExe 
This is displayed after reporting it's progress in installing,  I've never come across this error before, it's displayed no matter what option I choose regarding autostart.

I'm on win 10.
![autofps_fail](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/161671446/f139aec7-e422-4bc3-adff-bc74f09a6cbc)

**Comment by ResetXPDR** [comment] 2024-02-29 05:53
Even if you can't get auto install working, you should be able to install AutoFPS without it and just run it manually.

In any case, this is the same issue as reported [here](https://github.com/ResetXPDR/MSFS2020_AutoFPS/issues/5). 
An update to this is that if your EXE.xml file is missing, you need to go to your MSFS root directory, where it saves flight plans and manually create an EXE.xml file and save it there.

Here's a template of the content of mine, where you should just have to put in <username>, and this worked for another user:

<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="Launch" version="1,0">
  <Descr>Launch</Descr>
  <Filename>EXE.xml</Filename>
  <Disabled>False</Disabled>
  <Launch.ManualLoad>False</Launch.ManualLoad>
  <Launch.Addon>
    <Disabled>False</Disabled>
    <ManualLoad>False</ManualLoad>
    <Name>MSFS2020_AutoFPS</Name>
    <Path>C:\Users\<username>\AppData\Roaming\MSFS2020_AutoFPS\bin\MSFS2020_AutoFPS.exe</Path>
  </Launch.Addon>
</SimBase.Document>

**Comment by ResetXPDR** [comment] 2024-02-29 23:45
@SHAshton I am going to close this as the proposed resolution has worked for all who have encountered this issue so far.

**Comment by SHAshton** [comment] 2024-03-01 00:19
Hi8,
How can you close when I've asked questions about it which have not been answered?
regards
Steve
    On Thursday, 29 February 2024 at 23:45:45 GMT, ResetXPDR ***@***.***> wrote:  
 
 


Closed #8 as completed.

**Comment by SHAshton** [comment] 2024-03-01 00:24
Hi, I did type another question which I cannot see here, sure I posted it, it's regarding the location of the save flight plans as I have no idea where that would?
regards

Steve

**Comment by ResetXPDR** [comment] 2024-03-01 01:41
@SHAshton  I closed the issue because I have given you two workable options, either run the app without autostart or put the xml file in. Also, if you don't know how to locate your flight plan directory then you probably shouldn't be messing with xml files IMO.

**Comment by SHAshton** [comment] 2024-03-01 17:51
Hi,
There is no actual directory labelled as being for flight plan saves, that's why I didn't know. Running the app without autostartup caused the same problem so that wasn'ta fix in my case. As far as the saves location I'm not yet running things like the simbrief so it's it's just something I'm simply not yet aware of.In your 1st email there was an error in your copy and pasting, there was parts missing that you now have in your support guides on Github, many thanks for that, that error that I reported to you ahs not gone.
Did you know that even after this error being displayed that if you clicked on OK on the error that the app then reported it was installed ok.After adding the xml file there is still an error but it's different, I know it's a pain but wonder if you want to know what that error was and if you can ,make any sense of it as to why.
I ended up removing the app for the moment which in both cases caused the same errors, main reason I removed it was not because of the error but any lever that was being moved in the cockpits had what looked like 3 echos of the same lever around them, panning around the outside of the aircraft showed poor graphics but without the app I don't have any issues and wonder if the errors are a cause/ effect.220
regards
Steve
    On Friday, 1 March 2024 at 01:41:33 GMT, ResetXPDR ***@***.***> wrote:  
 
 


@SHAshton I closed the issue because I have given you two workable options, either run the app without autostart or put the xml file in. Also, if you don't know how to locate your flight plan directory then you probably shouldn't be messing with xml files IMO.

**Comment by ResetXPDR** [comment] 2024-03-01 18:25
@SHAshton

**Comment by ResetXPDR** [comment] 2024-03-01 18:35
@SHAshton I was so hasty in closing this issue as I thought you were only getting this issue when using one of the two autostart option and that I had addressed your issue with two resolution options. However, now rereading your original post you did say "it's displayed no matter what option I choose regarding autostart" which could also include do not configure autostart and I therefore see why you thought I was closing this issue prematurely and for that I am sorry. As such, I have reopened the issue.

Yes I am curious what the new error message was, so please let me know.

As for the lever echos and poor graphics, I have not heard of this before. If you do decide to reinstall the app again, can you send me the contents of the log file the app creates when it is behaving like this. Thanks.

**Comment by SHAshton** [comment] 2024-03-01 19:30
Hi,
I think graphics issue is possible not the lever themselves but would be the textures 'behind' the levers, rather than the quality of texture in front of a lever, ie in the direction it's being moved then the texture being redrawn. I it think it's that rather than the lever itself, the place I mainly noticed it was when moving the rotor brake in an heli, the background was downgraded in it's resolution which I guess is expected to reduce drawing time therefore maintaining or increasing fps at that time and with the lever itself moving it's not as noticeable in the levers own texture.
A screen shot with this 'new' error should be attached.
regards
Steve


    On Friday, 1 March 2024 at 18:35:47 GMT, ResetXPDR ***@***.***> wrote:  
 
 


@SHAshton I was so hasty in closing this issue as I thought you were only getting this issue when using one of the two autostart option and that I had addressed your issue with two resolution options. However, now rereading your original post you did say "it's displayed no matter what option I choose regarding autostart" which could also include do not configure autostart and I therefore see why you thought I was closing this issue prematurely and for that I am sorry. As such, I have reopened the issue.

Yes I am curious what the new error message was, so please let me know.

As for the lever echos and poor graphics, I have not heard of this before. If you do decide to reinstall the app again, can you send me the contents of the log file the app creates when it is behaving like this. Thanks.

**Comment by ResetXPDR** [comment] 2024-03-01 22:17
The screenshot didn't come through on my end.

**Comment by SHAshton** [comment] 2024-03-02 14:25
Ok I'll try again from pc later.
    On Friday, 1 March 2024 at 22:17:47 GMT, ResetXPDR ***@***.***> wrote:  
 
 


The screenshot didn't come through on my end.

**Comment by SHAshton** [comment] 2024-03-02 14:27
Just looked at the email I sent. The screen shot is attached but I'll send again when I get the pc on
    On Saturday, 2 March 2024 at 14:25:13 GMT, Steve Ashton ***@***.***> wrote:  
 
  Ok I'll try again from pc later.
    On Friday, 1 March 2024 at 22:17:47 GMT, ResetXPDR ***@***.***> wrote:  
 
 


The screenshot didn't come through on my end.

**Comment by SHAshton** [comment] 2024-03-02 16:39
Hi,
Ok, second try. It's showing attached at my end, it's only a small file 77.7kb in size.
It shows : exception 'system.xml.xmlexception' during autostartexe.
regards
Steve
    On Friday, 1 March 2024 at 22:17:47 GMT, ResetXPDR ***@***.***> wrote:  
 
 


The screenshot didn't come through on my end.

**Comment by ResetXPDR** [comment] 2024-03-02 19:05
Still not working. If you have been sending this by email, try posting directly on github instead.

**Comment by SHAshton** [comment] 2024-03-03 11:55
Ok cheers.
    On Saturday, 2 March 2024 at 19:06:09 GMT, ResetXPDR ***@***.***> wrote:  
 
 


Still not working. If you have been sending this by email, try posting directly on github instead.

**Comment by SHAshton** [comment] 2024-03-04 00:30
Hi,
I've uploaded the same screenshot here.
![xml xml](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/161671446/07e1e1fb-02b9-4fa1-bc80-bb5cd79fe317)

regards

Steve

**Comment by ResetXPDR** [comment] 2024-03-04 00:39
It looks like you were trying to use the "Remove Auto-Start" option when installing, which is still using the AutoStartExe function that was causing you issues with "Auto-Start with MSFS" and is why you are getting that error message.

Try rerunning the installer and choose the "Do not configure Auto-Start" option then Install.

**Comment by ResetXPDR** [comment] 2024-03-04 02:52
I just tried removing my EXE.xml then run the installer and I can confirm that you get the error message you have been seeing with the first "Remove Auto-Start" and third "Auto-Start with MSFS" install option, but it will install properly using the  "Do not configure Auto-Start" option.  

As such, your options are to either do this or create an EXE.xml file as described in detail in the readme and then you can use the "Auto-Start with MSFS" install option.

Please let me know when you've done either one and it works and I will close this issue.

**Comment by ResetXPDR** [comment] 2024-03-05 20:09
Two days with no response so I am going to assume this fixed it for you and close this issue.

**Closed by ResetXPDR** 2024-03-05 20:09 UTC
