### ISSUE TITLE
FPS SENSITIVITY NOT WORKING

### ISSUE THREAD

**Issue by FelipeThePilot** [ResetXPDR/MSFS2020_AutoFPS#71] opened 2024-10-04 14:11 UTC
So when i want to use autoFPS with lossless scaling (**I want LS to give me 144 fps so i set target fps 142**) and I set FPS **sensitivity to 1**, then after flying out of minimal tlod zone, the **tlod stays minimal** and doesnt increase even when i have stable 144 fps. 
If I want this to work with target fps 142, then minimal amout of fps sensitivity that i need to set is 5 - then the tlod increases during climb
If i want to work with sensitivity 1, then max amount of target fps i can set is 139, if i set more then 139 the tlod doesnt increase druing climb and whole flight stays minimal
Although, when for climb i set the config that is on 1st picture, and then when tlod reaches max change to config on 2nd picture, then tlod stays at max level (autofps doesnt lower it back to minimum)
When descending the 1 snensitivity works normal

When i dont use Lossless scaling, and cap my fps to 72 (I set target fps to 69), then set sensitivity to 1, then it works normal. So the problem is with the frame gen

Sorry for bad image quality
<img width="569" alt="1BEC911D-E617-4CD8-8EBB-EADE4ED35186" src="https://github.com/user-attachments/assets/4a1f3319-c1d2-4ea6-9a20-7d1de3d5adb6">
<img width="343" alt="{318CE388-AD2E-4A1E-8C9B-6BC2729CD129}" src="https://github.com/user-attachments/assets/6b78b65c-5634-449b-9a11-f45339572645">

**Comment by ResetXPDR** [comment] 2024-10-04 21:44
I've looked into this and the issue is that when you are using lossless scaling your settings are too tight to generate the minimum 1 TLOD amount to trigger a change in TLOD. In your first screenshot, it generates 0.6 TLOD which goes to the required 1 minimum, when rounded up, but in your second screenshot it generates 0.17 TLOD which rounds down to 0 and hence is the reason why you are not seeing any TLOD changes.

You say that when you don't use lossless scaling and set FPS cap to 72 and target FPS to 69, that is a much looser setting than what you have set for when using lossless scaling and is why it works. If you want to uses lossless scaling correctly with this app, you need to double EVERYTHING you had before ie double 72 FPS cap to 144, which you are already doing correctly, but you need to set target FPS to double 69, which is 138, not 142 like you have been doing. 

And before you say that a 6 FPS spread is now too much, it is EXACTLY what you were getting when this app didn't support lossless scaling because that 3 FPS spread was getting doubled to 6 FPS by lossless scaling but you weren't seeing it because AutoFPS was reporting pre lossless scaling FPS.

This is what your issue is, so to resolve it set your target FPS to 138.

**Comment by FelipeThePilot** [comment] 2024-10-05 07:59
Thank you very much, I will set my target to 138 and sensitivity to 1.
Also fun fact is, that with 2nd image, 3 days ago it was working perfectly. Then what I did is the autoFPS update, windows 24h2 update and amd adrenaline gpu software update. I dont think any of had any impact on the autoFPS but I do not know

**Comment by ResetXPDR** [comment] 2024-10-05 08:26
If you want to have a tighter FPS band then setting a higher sensitivity will make AutoFPS more responsive but with the possible side effect of slight stutters because of the greater potential TLOD changes. As every system is different, the only way to know for sure is to try out different sensitivity settings and pick the one that give the most pleasing results.

As your original issue is resolved by the response I gave above, I will now close this issue.

**Closed by ResetXPDR** 2024-10-05 08:26 UTC
